---
title: "Class 05: Data Visualization with GGPLOT"
author: "Ziheng Huang"
format: html
---

# First ggplot

Installation: install.packages(ggplot2)

```{r}
library(ggplot2)
ggplot()

```

mpg dataset:

```{r}
mpg
```

First plot: displ vs hwy:

data + aes + geoms:

```{r}
ggplot(mpg) + aes(x=displ,y=hwy) + geom_point()

```

Add more layers:

```{r}
ggplot(mpg) + 
  aes(x=displ,y=hwy) + 
  geom_point() + 
  geom_smooth(method="lm", se=FALSE)
```

load gene data

```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
```

Q: How many genes ?

```{r}
nrow(genes)
```

Q: What are the colnames ?

```{r}
colnames(genes)
```

plot gene data raw

```{r}
ggplot(genes) + 
    aes(x=Condition1, y=Condition2) +
    geom_point()

```

plot gene data:

```{r}
p <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2, col=State) +
    geom_point()
p
```

Q: how many is up/down regulated

```{r}

table(genes$State)
```

```{r}
p + scale_colour_manual( values=c("blue","gray","red") )

```

```{r}
p + scale_colour_manual(values=c("blue","gray","red")) +
    labs(title="Gene Expresion Changes Upon Drug Treatment",
         x="Control (no drug) ",
         y="Drug Treatment")
```
