---
title: "class06hw"
author: "Ziheng Huang"
format: html
---

Test run existing code

```{r}
library(bio3d) 
s1 <- read.pdb("4AKE")  
# kinase with drug 
s2 <- read.pdb("1AKE")  
# kinase no drug 
s3 <- read.pdb("1E4Y")  
# kinase with drug 
s1.chainA <- trim.pdb(s1, chain="A", elety="CA") 
s2.chainA <- trim.pdb(s2, chain="A", elety="CA") 
s3.chainA <- trim.pdb(s1, chain="A", elety="CA") 

s1.b <- s1.chainA$atom$b 
s2.b <- s2.chainA$atom$b 
s3.b <- s3.chainA$atom$b 

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor") 
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

Function Here !

Documentation:

input: your protein name ie. '4AKE'

The function will plot the graph for the input protein.

```{r}
plotProtein <- function(protein){
  s1 <- read.pdb(protein)  
  s1.chainA <- trim.pdb(s1, chain="A", elety="CA") 
  s1.b <- s1.chainA$atom$b 
  plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
}
```

Test function:

```{r}
plotProtein('4AKE')
plotProtein('1AKE')
plotProtein('1E4Y')
```
