---
title: "class06"
author: "Ziheng Huang"
format: html
---

## 

Test data:

```{r}
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)
```

```{r}
is.na(student3)
student3[is.na(student3)] <- 0
student3
```

Question 1:

grade() to find overall grade. lowest is dropped

```{r}
grade <- function(student){
  # 1. replace na with 0
  is.na(student)
  student[is.na(student)] <- 0
  # 2. get lowest and remove from sum
  scoresum = sum(student) - student[which.min(student)]
  # 3. find average
  overall = scoresum / (length(student) - 1)
  return(overall)
}
grade(student3)

```

Question 2:

Step 1: load csv into data:

```{r}
data <- read.csv("student_homework.csv")
data
```

Step 2: find the top student

```{r}
# calculate all the grades for all students
finalgrades <- apply(data[,2:6],1,grade)
# find highest score and print
which.max(finalgrades)
```

Student 18 has the highest score.

Question 3:

Step1: function: given a vector, replace the NA with 0 and find the average

```{r}
findAverage <- function(hw){
    is.na(hw)
    hw[is.na(hw)] <- 0
    return (mean(hw))
}
# testing
findAverage(c(100,100,NA))
```

Step 2: apply findAverage to every column and get the min value

```{r}
averageHWgrades <- apply(data[,2:6],2,findAverage)
averageHWgrades
which.min(averageHWgrades)
```

Lowest score is hw 2, it's the hardest.
